### ISSUE TITLE
View more option required against the description, when it exceeds 10 lines 

### ISSUE THREAD

**Issue by ashika123** [ajency/Wine-subscription#12]
Current behavior:
The entire description entered is displayed 

Expected behavior: View more should be displayed when the description exceeds 10 lines 
![view more](https://cloud.githubusercontent.com/assets/9797052/25884003/d5fa7282-356c-11e7-9405-f172f496c8b7.jpg)

**Comment by ajajrajguru** [comment]
View more added.

**Comment by ashika123** [comment]
Tested
