### ISSUE TITLE
"Continue Shopping" or "Return to shop" should redirect the user to the wine packs page

### ISSUE THREAD

**Issue by Valenie** [ajency/Wine-subscription#74]
![image](https://cloud.githubusercontent.com/assets/19943710/26387991/76747a3e-406f-11e7-9d88-1bb4cdaebc05.png)

**Comment by Valenie** [comment]
@ajajrajguru : Continue shopping still redirects to "The Club" page

**Comment by ajajrajguru** [comment]
Link added for continue shopping.
