### ISSUE TITLE
Even when there is saved tab for one product, when the user tries to add the same tab to the other the tab is not displayed

### ISSUE THREAD

**Issue by Valenie** [ajency/Wine-subscription#78]
![image](https://cloud.githubusercontent.com/assets/19943710/26438427/a1d09d62-4140-11e7-9d07-a61436b5e736.png)

**Comment by ajajrajguru** [comment]
@Valenie Saved tabs doesn't work that way you need to add a tab in **settings** --> **Custom product tabs** section and when your done adding tab you can select saved tab for product which you are adding for and one thing to note here is while adding saved tab for product you need to check **override saved tab** checkbox for product which gives you to override tab content.
